---
title: 异常捕获
date: 2021-07-08 17:50:47
categories:
- JavaScript
comments: true
---

## 代码执行的错误捕获

### try...catch

- 能捕获到代码执行的错误，捕获不到语法的错误
- 无法处理异步中的错误
- 可以拿到出错的信息：堆栈、出错的文件、行号、列号
- try...catch 包裹，影响代码可读性



### window.onerror

```js
window.onerror = function(message, source, lineno, colno, error) { ... }

函数参数：

*   message：错误信息（字符串）。可用于HTML onerror=""处理程序中的event。
*   source：发生错误的脚本URL（字符串）
*   lineno：发生错误的行号（数字）
*   colno：发生错误的列号（数字）
*   error：Error对象

若该函数返回true，则阻止执行默认事件处理函数，如异常信息不会在console中打印。没有返回值或者返回值为false的时候，异常信息会在console中打印
```

- 能捕获同步、异步 的错误
- 能捕获代码运行、语法的错误
- 可以拿到出错的信息：堆栈、出错的文件、行号、列号
- onerror 主要是来捕获预料之外的错误，try...catch 用来在可预见情况下监控特定的错误，两者结合使用更加高效
- 跨域的资源需要特殊头部支持
- 函数返回 true的时候，异常不会向上抛出
- 监听不到资源加载的报错
- 事件处理函数只能声明一次，不会重复执行多个回调



### window.addEventListener('error')

```js
window.addEventListener('error', (msg, url, row, col, error) => {})
```

- 可以监听到资源加载错误，但无法判断 http 状态
- 可以注册多个事件处理函数



### window.addEventListener('unhandledrejection')

- 捕获 promise 错误，当 promise 被 reject 且没有 reject 处理器的时候，出触发 unhandledrejection 事件
- 可能发生在 window 下，但也可能发生在 Worker
- 对于调试回退错误处理非常有用



## 资源加载的错误捕获

- imgObj.onerror()

- performance.getEntries() 捕获到成功加载的资源，对比可以间接的捕获错误

- window.addEventListener('error', fu, true) 

  > 当资源（如img或script）加载失败，加载资源的元素会触发一个Event接口的error事件，并执行该元素上的onerror()处理函数。这些error事件不会向上冒泡到window，但可以在捕获阶段被捕获
  > 因此如果要全局监听资源加载错误，需要在捕获阶段捕获事件



## Vue、React 的错误捕获 

Vue：errorHandler

React：componentDidCatch