---
title: 手写Promise
date: 2021-07-02 18:11:37
categories:
  - ES6
comments: true
---

## 前言

发现之前记录的手写 Promise 教程太简单了，发现网上很多关于 [promisesA+规范 ](https://promisesaplus.com/)的书写，先记录下来~

<!--more -->

## 代码

```js
const isFunction = (fn) => typeof fn === 'function';
const isObject = (obj) => typeof obj === 'object';

class myPromise {
  // 构造器
  // executor: 执行器函数， 传入就执行
  // 有两个参数：resolve、reject，是预先定义好的私有方法
  constructor(executor) {
    // 初始化 state 为等待态
    this.state = "pending";
    // 成功的值
    this.value = undefined;
    // 失败的原因
    this.reason = undefined;
    // 成功存放的数组：[1]
    // 1. 当resolve在setTomeout内执行，then时state还是pending等待状态 我们就需要在then调用的时候，将成功和失败存到各自的数组，一旦reject或者resolve，就调用它们
    // 2. 假如使用 then 注册了多个回调函数，则它们会依次执行
    this.onResolvedCallbacks = [];
    // 失败存放法数组
    this.onRejectedCallbacks = [];

    /**
     * 使状态变更为 fulfilled
     * 调用注册的事件，注意调用后进行清除 
     * @param value
     * @returns
     */
    let resolve = (value) => {
      const cb = () => {
        // state 改变
        if (this.state !== "pending") {
          return
        }
        // 一旦resolve执行，调用成功数组的函数
        while (this.onResolvedCallbacks.length) {
          const fn = this.onResolvedCallbacks.shift();
          fn && fn(value);
        }
        // resolve 调用后，state 转化为成功态
        this.state = "fulfilled";
        // 储存成功的值
        this.value = value;
      }
      // 使任务变成异步的
      queueMicrotask(() => cb());
    };

    /**
     * 使状态变更为 rejected
     * @param value
     */
    let reject = (reason) => {
      const cb = () => {
        // state 改变
        if (this.state !== "pending") {
          return
        }
        // 一旦reject执行，调用失败数组的函数
        while (this.onRejectedCallbacks.length) {
          const fn = this.onRejectedCallbacks.shift();
          fn && fn(reason);
        }
        // reject 调用后，state 转化为失败态
        this.state = "rejected";
        // 储存失败的原因
        this.reason = reason;
      }
      // 使任务变成异步的
      queueMicrotask(() => cb());
    };

    // 如果executor执行报错，直接执行reject
    try {
      executor(resolve, reject);
    } catch (err) {
      reject(err);
    }
  }

  /**
   * 根据当前不同状态来执行对应逻辑
   * 如果在默认状态就是注册对应事件
   * 如果状态变化则是执行对应事件
   * @param onFulfilled
   * @param onRejected
   * @returns
   */
  then(onFulfilled, onRejected) {
    // 传入参数不是函数，或者未传的情况，就给定默认处理函数
    onFulfilled = isFunction(onFulfilled) ? onFulfilled : value => value;
    onRejected = isFunction(onRejected) ? onRejected : err => {
      throw err
    };

    // newPromise（默认返回的promise）
    // x（我们自己return的对象）
    // resolve、reject 是 newPromise 的
    const resolvePromise = (promise, x, resolve, reject) => {
      // 返回的 promise 不可以是当前的 promise 否则会造成死循环
      if (promise === x) {
        reject(new TypeError('Chaining cycle detected for promise #<Promise>'));
      }
      // 对可能是 thenable 接口实现的对象判断
      if (x !== null && (isObject(x) || isFunction(x))) {
        try {
          // A+规定，声明 then = x的then方法
          let thenCb;
          thenCb = x.then;
          // 如果是 thenable 的对象，则调用其 then 方法
          // 这一步涵盖了 Promise 实例的可能性
          if (isFunction(thenCb)) {
            let isCalled = false;
            try {
              thenCb.call(
                x, // 指向当前函数或对象
                (y) => {
                  // 如果 resolvePromise 和 rejectPromise 都可能被调用
                  // 则只需调用第一次（resolvePromise 或 rejectPromise），后续无需再执行
                  if (isCalled) return;
                  isCalled = true;
                  // 传入当前函数，以实现递归展开调用
                  resolvePromise(promise, y, resolve, reject);
                },
                (r) => {
                  // 对应前面任意的调用之后，就不再只需后续逻辑
                  if (isCalled) return;
                  isCalled = true;
                  reject(r);
                }
              )
            } catch (error) {
              if (isCalled) return;
              reject(error);
            }
          } else {
            resolve(x);
          }
        } catch (error) {
          return reject(error);
        }
      } else {
        resolve(x);
      }
    }
    // 声明返回的newPromise
    let newPromise = new myPromise((resolve, reject) => {
      //  封装完成回调函数
      const handleFulfilled = (val) => {
        try {
          const x = onFulfilled && onFulfilled(val);
          resolvePromise(newPromise, x, resolve, reject);
        } catch (err) {
          // 如果当前执行逻辑内发生异常，则抛出异常
          reject(err);
        };
      };

      // 封装错误回调函数
      const handleRejected = (val) => {
        try {
          const x = onRejected && onRejected(val);
          // resolvePromise函数，处理自己return的promise和默认的newPromise的关系
          resolvePromise(newPromise, x, resolve, reject);
        } catch (err) {
          reject(err);
        }
      }

      switch (this.state) {
        case 'pending':
          this.onResolvedCallbacks.push(handleFulfilled);
          this.onRejectedCallbacks.push(handleRejected);
          break;
        case 'fulfilled':
          handleFulfilled(this.value);
          break;
        case 'rejected':
          handleRejected(this.reason);
          break;
      }
    });
    // 返回promise，完成链式
    return newPromise;
  }

  // 本质上 catch 方法是 then 第二个参数也就是错误回调函数的语法糖
  catch (fn) {
    return this.then(null, fn);
  }

  //
  finally(fn) {
    return this.then(
      // 完成回调时，执行注册函数，并且将原来的值传递下去
      // 封装 myPromise 类，再调用 then 方法传递
      val => myPromise.resolve(fn && fn()).then(() => val),
      // 异常回调时，执行注册函数，并且抛出异常
      err => myPromise.resolve(fn && fn()).then(() => {
        throw err
      })
    );
  }


  /**
   * 判断是否是当前类的实例
   * @param promise
   * @returns
   */
  static is(promise) {
    return promise instanceof myPromise;
  }
}


//resolve方法
myPromise.resolve = function (val) {
  // 如果传入的已经是 Promise 实例，则不必再进行处理
  if (myPromise.is(val)) {
    return val;
  }
  return new myPromise((resolve) => {
    // 如果参数是thenable对象时，Promise.resolve方法会将这个对象转为Promise对象，然后就立即执行thenable对象的then方法。
    if (value && isObject(value) && isFunction(value.then)) {
      return queueMicrotask(() => {
        try {
          val.then(resolve, reject);
        } catch (error) {
          reject(error);
        }
      });
    }
    resolve(value);
  });
};

//reject方法
myPromise.reject = function (val) {
  return new myPromise((resolve, reject) => {
    reject(val);
  });
};

//race方法
myPromise.race = function (promise) {
  return new myPromise((resolve, reject) => {
    for (let i = 0; i < promises.length; i++) {
      // 如果不是 Promise 实例，则需要包装一份；
      // 但因为直接包装 Promise 类的效果是幂等的，所以这里不需要判断，直接处理即可
      myPromise.resolve(promises[i]).then(
        (val) => {
          resolve(val);
        },
        (err) => {
          reject(err);
        }
      );
    }
  });
};

//all方法(获取所有的promise，都执行then，把结果放到数组，一起返回)
myPromise.all = function (promises) {
  return new myPromise((resolve, reject) => {
    let resultCount = 0;
    let results = []

    for (let i = 0; i < promises.length; i++) {
      myPromise.resolve(promises[i]).then(
        (val) => {
          resultCount++;
          results[i] = val;
          if (resultCount === promises.length) {
            resolve(results);
          }
        },
        (err) => {
          reject(err);
        }
      );
    }
  });
};

myPromise.allSettled = function (promises) {
  return new myPromise((resolve, reject) => {
    let resultCount = 0;
    let results = []

    for (let i = 0; i < promises.length; i++) {
      myPromise.resolve(promises[i])
        .then(
        (val) => {
          results[i] = {
            status: "fulfilled",
            value: val,
          };
        },
        (err) => {
          results[i] = {
            status: "rejected",
            reason: err,
          };
        }
      )
        .finally(() => {
        if (++resultCount === promises.length) {
          resolve(results);
        }
      });
    }
  });
};

// 第三方验证
myPromise.deferred = function () {
  let defer = {};
  defer.promise = new myPromise((resolve, reject) => {
    defer.resolve = resolve;
    defer.reject = reject;
  });
  return defer;
}

module.exports = myPromise;
```

### 注释

成功存放的数组：

1. 当resolve在setTomeout内执行，then时state还是pending等待状态 我们就需要在then调用的时候，将成功和失败存到各自的数组，一旦reject或者resolve，就调用它们

   ```js
   let p = new Promise((resolve, reject) => {
     setTimeout(resolve, 1000, 'success');
   });
   p.then(
     res => {
       console.log(res);
       return `${res} again`;
     }
   )
     .then(
     res => console.log(res)
   );
   // 连续
   // success
   // success again
   ```

2. 假如使用 then 注册了多个回调函数，则它们会依次执行

   ```js
   let p2 = new Promise((resolve, reject) => {
       resolve(1)
   })
   p2.then(value => {
       console.log('第一个', value)
   })
   p2.then(value => {
       console.log('第二个', value)
   })
   ```



## 扩展打印题

```js
new Promise(resolve => {
  resolve(1);
  Promise.resolve({
    then: function (resolve, reject) {
      console.log(2);
      resolve(3)
    }
  }).then(t => console.log(t))
  console.log(4);
}).then(t => console.log(t));
console.log(5);
// 4 5 2 1 3

// new Promise([executor]) 首先执行，进入 executor 函数。
// 第一行就已经 resolve(1); 这个 Promise 马上由 pending 状态过渡到 fulfill 状态。这个带 1 的任务被压到前面提到的栈中。
// 继续执行 executor 剩下的代码。Promise.resolve([object])，这个带 [object] 的任务被压到栈中。
// 遇到第一个 console.log(4);。
// 第二个 console.log(5);。
// 本轮的平台代码运行完毕，开始清栈。
// 处理带 [object] 的任务，因为这个 object 中有 then 方法，直接当新的 executor 调用。
// 注意 executor 是同步的，这里马上遇到 console.log(2)。
// 接着 resolve(3)，因为本轮的栈还没处理完（Promise 底层也属于“平台代码”），这个带 3 的任务被压到下一轮的栈中。
// 处理带 1 的任务，.then(t => console.log(t)); 打印 1。
// 栈空，马上清理下一轮的栈。
// 打印 3。
// 处理完毕。
```



## 参考文章

[BAT 前端经典面试问题：史上最最最详细的手写 Promise 教程](https://juejin.cn/post/6844903625769091079#heading-9)

[两天时间，实现自己的 Promise](https://mp.weixin.qq.com/s/wveqotJEMHBMn27FAMqIBg)
