---
title: async、await原理
date: 2021-11-22 17:23:37
categories:
- ES6
comments: true
---

## 用处

> 用同步方式，执行异步操作

<!-- more -->



## 使用例子

```js
// 模拟接口请求
function request(num) { 
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(num * 2)
    }, 1000)
  })
}

// 没有 async await，模拟同步
// 需求一：先请求完接口1，再去请求接口2
request(1).then(res1 => {
  console.log(res1) // 1秒后 输出 2
  request(2).then(res2 => {
    console.log(res2) // 2秒后 输出 4
  })
})

// 需求二：先请求完接口1，再拿接口1返回的数据，去当做接口2的请求参数
request(5).then(res1 => {
  console.log(res1) // 1秒后 输出 10
  request(res1).then(res2 => {
    console.log(res2) // 2秒后 输出 20
  })
})

// async await
async function fn () {
  const res1 = await request(5)
  const res2 = await request(res1)
  console.log(res2) // 2秒后输出 20
}
fn()
```

![图片](https://mmbiz.qpic.cn/mmbiz_png/TZL4BdZpLdgBdibGsQ5icVMDdDPDRJ7KiaicYNhI2bD4P5DbxnNcJdrNbUkS0G1WTvrFLP5umotnHxGVJ4rblYjadQ/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)



如果 await 后面跟的不是 promise，就没有同步的效果

```js
function request(num) { // 去掉Promise
  setTimeout(() => {
    console.log(num * 2)
  }, 1000)
}

async function fn() {
  await request(1) // 2
  await request(2) // 4
  // 1秒后执行完  同时输出
}
fn()
```



async 执行完会自动返回一个状态为 `fulfilled`，值为 undefined 的 Promise。如果 return 一个值，那么 Promise 的值就是 返回的值

```js
async function fn () {}
console.log(fn) // [AsyncFunction: fn]
console.log(fn()) // Promise {<fulfilled>: undefined}

async function fn (num) {
  return num
}
console.log(fn) // [AsyncFunction: fn]
console.log(fn(10)) // Promise {<fulfilled>: 10}
fn(10).then(res => console.log(res)) // 10
```



## generator函数 

### 基本用法

- generator函数 比普通函数多了 * 
- yield：函数执行的中途暂停点
- next 方法：执行后会返回一个对象，对象有 value 和 done 两个属性
  - value：暂停点后面接的值，也就是yield后面接的值
  - done：是否generator函数已走完，没走完为false，走完为true

```js
function* gen() {
  yield 1
  yield 2
  yield 3
  // return 4
}
const g = gen()
console.log(g.next()) // { value: 1, done: false }
console.log(g.next()) // { value: 2, done: false }
console.log(g.next()) // { value: 3, done: false }
console.log(g.next()) // { value: undefined, done: true } // 最后一个值是什么，取决于是否有返回值
// console.log(g.next()) // { value: 4, done: true }
```

![图片](https://mmbiz.qpic.cn/mmbiz_png/TZL4BdZpLdgBdibGsQ5icVMDdDPDRJ7Kiaic88XNx9sz7w6gHMWAL0AGQVUaFTEvMj8QEgibpBcLuPJ1e5PBnIrdQAw/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)



### yield 后面接函数

到了对应暂停点yield，会马上执行此函数，并且该函数的执行返回值，会被当做此暂停点对象的`value`

```js
function fn(num) {
  console.log(num)
  return num
}
function* gen() {
  yield fn(1)
  yield fn(2)
  return 3
}
const g = gen()
console.log(g.next()) 
// 1
// { value: 1, done: false }
console.log(g.next())
// 2
//  { value: 2, done: false }
console.log(g.next()) 
```



### yield 后面接 Promise

前两个的 value 都是 pending 状态的 Promise 对象

```js
function fn(num) {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(num)
    }, 1000)
  })
}
function* gen() {
  yield fn(1)
  yield fn(2)
  return 3
}
const g = gen()
console.log(g.next()) // { value: Promise { <pending> }, done: false }
console.log(g.next()) // { value: Promise { <pending> }, done: false }
console.log(g.next()) // { value: 3, done: true }
```

![图片](https://mmbiz.qpic.cn/mmbiz_png/TZL4BdZpLdgBdibGsQ5icVMDdDPDRJ7KiaiceBP8TfDAMPCjMCkicEs9g0kq0D3qnCHRWDNVOM9cNlLYTzQQgWAD60A/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

怎么拿到两个 Promise 的结果呢？

```js
const g = gen()
const next1 = g.next()
next1.value.then(res1 => {
  console.log(next1) // 1秒后输出 { value: Promise { 1 }, done: false }
  console.log(res1) // 1秒后输出 1

  const next2 = g.next()
  next2.value.then(res2 => {
    console.log(next2) // 2秒后输出 { value: Promise { 2 }, done: false }
    console.log(res2) // 2秒后输出 2
    console.log(g.next()) // 2秒后输出 { value: 3, done: true }
  })
})
```

![图片](https://mmbiz.qpic.cn/mmbiz_png/TZL4BdZpLdgBdibGsQ5icVMDdDPDRJ7KiaicDYVNDdMNfgVct8Z6GibKyIhlBm7pOIibUTN3toJZsRByqNgRicpSFdbrw/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)



### next函数传参

可以用 `next方法` 来传参，并且可以通过 `yield` 来接收这个参数，注意两点

- 第一次 next 传参是没用的，只有从第二次开始 next 传参才有用
- next 传值时，要记住顺序是，先右边 yield，后左边接收参数

```js
function* gen() {
  const num1 = yield 1
  console.log(num1)
  const num2 = yield 2
  console.log(num2)
  return 3
}
const g = gen()
console.log(g.next()) // { value: 1, done: false }
console.log(g.next(11111))
// 11111
//  { value: 2, done: false }
console.log(g.next(22222)) 
// 22222
// { value: 3, done: true }
```

![图片](https://mmbiz.qpic.cn/mmbiz_png/TZL4BdZpLdgBdibGsQ5icVMDdDPDRJ7Kiaicbf0HgJqicU1vqpyqcertshiaTbYMGMwiarttzKPLNEJsSFlZsRHO4l3Og/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)



### Promise+next传参

上面两种组合在一起

```js
function fn(nums) {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(nums * 2)
    }, 1000)
  })
}
function* gen() {
  const num1 = yield fn(1)
  const num2 = yield fn(num1)
  const num3 = yield fn(num2)
  return num3
}
const g = gen()
const next1 = g.next()
next1.value.then(res1 => {
  console.log(next1) // 1秒后同时输出 { value: Promise { 2 }, done: false }
  console.log(res1) // 1秒后同时输出 2

  const next2 = g.next(res1) // 传入上次的res1
  next2.value.then(res2 => {
    console.log(next2) // 2秒后同时输出 { value: Promise { 4 }, done: false }
    console.log(res2) // 2秒后同时输出 4

    const next3 = g.next(res2) // 传入上次的res2
    next3.value.then(res3 => {
      console.log(next3) // 3秒后同时输出 { value: Promise { 8 }, done: false }
      console.log(res3) // 3秒后同时输出 8

       // 传入上次的res3
      console.log(g.next(res3)) // 3秒后同时输出 { value: 8, done: true }
    })
  })
})
```



![图片](https://mmbiz.qpic.cn/mmbiz_png/TZL4BdZpLdgBdibGsQ5icVMDdDPDRJ7KiaicePOVxcicC9MUicT6ZibDgyCVk8Dt8gghh1tRLial1iakFLFkW162icPt0hcw/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)



## 实现 async/await

![图片](https://mmbiz.qpic.cn/mmbiz_png/TZL4BdZpLdgBdibGsQ5icVMDdDPDRJ7KiaicLkkdiaOrcKURicv22ojr9UhVf04iaWNHzS2KyHwJ7eWCeVEseo4CMN9aw/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

和 asycn/await 区别在于

- gen函数执行返回值不是Promise，asyncFn执行返回值是Promise
- gen函数需要执行相应的操作，才能等同于asyncFn的排队效果
- gen函数执行的操作是不完善的，因为并不确定有几个yield，不确定会嵌套几次



### 返回值 Promise

```js
function* gen() {

}

// 高阶函数：接收一个函数，返回一个函数
function generatorToAsync (generatorFn) {
  return function () {
    return new Promise((resolve, reject) => {

    })
  }
}

const asyncFn = generatorToAsync(gen)

console.log(asyncFn()) // Promise
```



### 加入一系列操作

```js
function fn(nums) {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(nums * 2)
    }, 1000)
  })
}
function* gen() {
  const num1 = yield fn(1)
  const num2 = yield fn(num1)
  const num3 = yield fn(num2)
  return num3
}
function generatorToAsync(generatorFn) {
  return function () {
    return new Promise((resolve, reject) => {
      const g = generatorFn()
      const next1 = g.next()
      next1.value.then(res1 => {

        const next2 = g.next(res1) // 传入上次的res1
        next2.value.then(res2 => {

          const next3 = g.next(res2) // 传入上次的res2
          next3.value.then(res3 => {

            // 传入上次的res3
            resolve(g.next(res3).value)
          })
        })
      })
    })
  }
}

const asyncFn = generatorToAsync(gen)

asyncFn().then(res => console.log(res)) // 3秒后输出 8
```

已经实现了以下 的 async/await 结果

```js
async function asyncFn() {
  const num1 = await fn(1)
  const num2 = await fn(num1)
  const num3 = await fn(num2)
  return num3
}
asyncFn().then(res => console.log(res)) // 3秒后输出 8
```



### 完善代码

await 的个数是不确定的，需要把上面的代码弄成通用的

```js
function fn(nums) {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(nums * 2)
    }, 1000)
  })
}
function* gen() {
  const num1 = yield fn(1)
  const num2 = yield fn(num1)
  const num3 = yield fn(num2)
  return num3
}
function generatorToAsync(generatorFn) {
  return function() {
    const gen = generatorFn.apply(this, arguments) // gen有可能传参

    // 返回一个Promise
    return new Promise((resolve, reject) => {

      function go(key, arg) {
        let res
        try {
          res = gen[key](arg) // 这里有可能会执行返回reject状态的Promise
        } catch (error) {
          return reject(error) // 报错的话会走catch，直接reject
        }

        // 解构获得value和done
        const { value, done } = res
        if (done) {
          // 如果done为true，说明走完了，进行resolve(value)
          return resolve(value)
        } else {
          // 如果done为false，说明没走完，还得继续走

          // value有可能是：常量，Promise，Promise有可能是成功或者失败
          return Promise.resolve(value).then(val => go('next', val), err => go('throw', err))
        }
      }

      go("next") // 第一次执行
    })
  }
}

const asyncFn = generatorToAsync(gen)

asyncFn().then(res => console.log(res))
```



### 示例

`async/await`版本

```js
async function asyncFn() {
  const num1 = await fn(1)
  console.log(num1) // 2
  const num2 = await fn(num1)
  console.log(num2) // 4
  const num3 = await fn(num2)
  console.log(num3) // 8
  return num3
}
const asyncRes = asyncFn()
console.log(asyncRes) // Promise
asyncRes.then(res => console.log(res)) // 8
```

使用`generatorToAsync函数`的版本

```js
function* gen() {
  const num1 = yield fn(1)
  console.log(num1) // 2
  const num2 = yield fn(num1)
  console.log(num2) // 4
  const num3 = yield fn(num2)
  console.log(num3) // 8
  return num3
}

const genToAsync = generatorToAsync(gen)
const asyncRes = genToAsync()
console.log(asyncRes) // Promise
asyncRes.then(res => console.log(res)) // 8
```



## 参考

[7张图，20分钟完全搞定async/await原理！（收藏）](https://mp.weixin.qq.com/s/1M0YX6aomZIKQeHIzl5U1w)